export {default as Dashboard } from "./Dashboard/Dashboard"
export {default as Errorpage } from "./Errorpage/Errorpage"
export {default as Favourites } from "./Favourites/Favourites"
export {default as Login } from "./Login/Login"
export {default as Register } from "./Register/Register"
export {default as Showpage } from "./Showpage/Showpage"
export {default as Write } from "./Write/Write"
export {default as ReadingPage} from "./ReadingPage/reading"